using MoysIQPlatform.Shared.Models.Questions;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace MoysIQPlatform.Shared.Models.Accounts;

public class Employee
{
	[Key]
	public int Id { get; set; }

	[Required]
	public string FullName { get; set; } = string.Empty;

	[Required, EmailAddress]
	public string Email { get; set; } = string.Empty;

	// Stores the hashed password as a string (generated by PasswordHasher<Employee>)
	[Required]
	public string PasswordHash { get; set; } = string.Empty;

	public string Department { get; set; } = string.Empty;

	// Role can be "User", "Admin", etc.
	public string Role { get; set; } = "User";

	public string WorkLocation { get; set; } = string.Empty;

	public string PhoneNumber { get; set; } = string.Empty;

	public string Gender { get; set; } = string.Empty;

	// Indicates whether the employee account is approved by an admin
	public bool IsApproved { get; set; } = false;

	// The UTC date and time when the employee was created
	public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

	// Questions created by this employee (ignored in API JSON responses)
	[JsonIgnore]
	public List<Question> Questions { get; set; } = new();
}
